import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import SyncUserWithConvex from "@/components/SyncUserWithConvex";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ticket Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConvexClientProvider>
          <ClerkProvider>
            <Header />
            <SyncUserWithConvex />
            {children}

            <Toaster />

            <footer className="border-t bg-white  h-20">
              <div className="container mx-auto px-4 py-6">
                <div className="flex flex-col md:flex-row justify-between items-center">
                  <p className="text-sm text-gray-600 mb-4 md:mb-0">
                    © {new Date().getFullYear()} Ticketer. All
                    rights reserved.
                  </p>
                  <nav>
                    <ul className="flex flex-wrap justify-center gap-4 text-sm text-gray-600">
                      
                      <li>
                        <Link href="/contact" className="hover:text-blue-600">
                          Contact
                        </Link>
                      </li>
                      <li>
                        <Link href="/terms" className="hover:text-blue-600">
                          Terms & Conditions
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/cancellation"
                          className="hover:text-blue-600"
                        >
                          Cancellation Policy
                        </Link>
                      </li>
                     
                    </ul>
                  </nav>
                </div>
              </div>
            </footer>
          </ClerkProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
